### ISSUE TITLE
Fehler bei Installation auf 32-Bit-Systemen

### ISSUE THREAD

**Issue by J-U-B** [J-U-B/OPSI-dfn_java#3]
Java8 (genauer: zumindest jre8) lässt sich nicht auf 32-Bit Systemen installieren. Die Scripts sehen im Prinzip so aus, als sei der Fall abgedeckt, eine explizite Abfrage mit Ergebnis "Error: OS is not a 64 Bit System" bricht die Installation dann aber frühzeitig ab. Ist das ein Fehler oder ist ein reines 32-Bit System tatsächlich nicht mehr unterstützt? Das Testen auf 32-Bit könnte ich notfalls übernehmen.  
(Michael Decker)

**Comment by J-U-B** [comment]
Geaendertes Verhalten:
* Fuer reine 64-Bit-OPSI-Pakete ("ifdef_x64_only"; Std. Java10) erfolgt der sofortige Abbruch auf einem 32-Bit-System.
* Die angeforderte Installation eines 64-Bit-Java auf einem 32-Bit-System fuehrt zu einem Fehler mit Abbruch
* Die angeforderte Installation eines 32- und 64-Bit-Java auf einem 64-Bit-System fuehrt zu einer Fehlermeldung, installiert jedoch die 32-Bit-Version.

**Comment by mdecker** [comment]
Es scheint noch einen Fehler in der Deinstallationslogik zu geben, weil auch auf dem x86-System noch versucht wird, den x64-Zweig zu durchsuchen:
```
(678)     [6] [Jul 26 09:53:33:826] [test_dfn_jre8]       ~~~~~~~ Start Sub ~~~~~~~  Sub_search_registry_uninstall_keys
(679)     [6] [Jul 26 09:53:33:828] [test_dfn_jre8]       Set  $RegSearchOpts$ = '/s /d  /f "' + $SearchPattern$ + '"'
(680)     [6] [Jul 26 09:53:33:828] [test_dfn_jre8]         The value of the variable "$RegSearchOpts$" is now: "/s /d  /f "Java 8 ""
(681)     [6] [Jul 26 09:53:33:828] [test_dfn_jre8]       Set  $TempList$ =                           getOutStreamFromSection ("ExecWith_UninstSearch_registry_query_64 'C:\Windows\cmd64.exe' /C")
(682)     [6] [Jul 26 09:53:33:831] [test_dfn_jre8]         
(683)     [6] [Jul 26 09:53:33:831] [test_dfn_jre8]         Execution of ExecWith_UninstSearch_registry_query_64 'C:\Windows\cmd64.exe' /C
(684)     [7] [Jul 26 09:53:33:832] [test_dfn_jre8]           Save to file with encoding: system
(686)     [2] [Jul 26 09:53:33:836] [test_dfn_jre8]           Error: Could not execute "C:\Windows\cmd64.exe"  /C "c:\opsi.org\tmp\_opsiscript_Wl10Gd34.cmd"  , error  (Das System kann die angegebene Datei nicht finden.)
(687)     [7] [Jul 26 09:53:33:836] [test_dfn_jre8]         The file: c:\opsi.org\tmp\_opsiscript_Wl10Gd34.cmd has been deleted
```

**Comment by J-U-B** [comment]
Nachbesserung mit Commit aedb453

**Comment by J-U-B** [comment]
Der Fehler ist mit aedb453 behoben.
(OK-Feedback von _mdecker_ am 26.07.2018.)
